### ISSUE TITLE
Use prefix when creating Discovery project

### ISSUE THREAD

**Issue by in-1911** [terraform-ibm-modules/terraform-ibm-rag-sample-da#105]
### Description

When the module is creating the Discovery project, a fixed name `gen-ai-rag-sample-app-project` us used making it difficult to deploy multiple applications using the same Discovery service instance.

The module / DA should use the provided prefix parameter when constructing the project name as well as provide an optional parameter to control the project name.

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by brendankellyibm** [comment]
Should be resolved by #113, reopen if there's any problems
