### ISSUE TITLE
add logic that triggers the initial ci pipeline run as final step of the da

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-rag-sample-da#12]

**Comment by vburckhardt** [comment]
Brendan working on it already

**Comment by brendankellyibm** [comment]
I have logic working that creates and triggers a webhook to start the CI portion of the toolchain.

I also have a trigger created to promote the inventory entries once CI is complete. 

Currently trying to understand how to automatically approve/merge the resulting pull request so the full CD pipeline can run.
