### ISSUE TITLE
Make app-url available for CC pipeline

### ISSUE THREAD

**Issue by in-1911** [terraform-ibm-modules/terraform-ibm-rag-sample-da#172]
### Description

The SCC checks in AI Guardrails profile require a dynamic scan in the CC pipeline run.
To enable the dynamic scanning, the following properties need to be set in the pipeline or a at least the manual trigger:
- `opt-in-dynamic-scan = 1` (or any non-empty value)
- `opt-in-dynamic-ui-scan = 1` (or any non-empty value)
- `app-url = https://rag-sample-app.<code-engine assigned subdomain>.<code-engine region>.codeengine.appdomain.cloud/`

The app-url needs to be retrieved from the application in CD project, presumably in the CD pipeline run. 
Likely it needs to be stored in an inventory to be able to fetch it in CC run.

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by brendankellyibm** [comment]
Initial thoughts:

- It may be difficult to automate passing the `app-url` parameter between the CD and CC pipelines, as the CD pipeline is less configurable than CI and it may be problematic to add information to the inventory from there.
- Passing the `app-url` parameter from CI (ie the 'dev' instance) is easier, as we can include that information in the inventory.

**Comment by in-1911** [comment]
We can start with that, at least some dynamic scan results will be in CC.
Is there a different way to pass the app url? Inventory may not be the proper channel as well - it seems to be more related to the application components / artifacts, so may be only CI is supposed to update it?

**Comment by ocofaigh** [comment]
From Brendan:

> This one's complete from what I remember. We store it in the inventory repo.
