### ISSUE TITLE
Storage delegation API failure

### ISSUE THREAD

**Issue by in-1911** [terraform-ibm-modules/terraform-ibm-rag-sample-da#200]
The dataplatform API is failing with a new required attribute and it would affect the storage delegation module call in 

https://github.com/terraform-ibm-modules/terraform-ibm-rag-sample-da/blob/e9210c6f188155d93b01ac1441228bcdb8542590/modules/watson-machine-learning/main.tf#L19

Once /terraform-ibm-modules/terraform-ibm-watsonx-saas-da/issues/190 is fixed, this should reference and updated version.

**Comment by alex-reiff** [comment]
Watson team pushed this breaking change then rolled it back. Draft PR exists if they push the change again: https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/pull/191
