### ISSUE TITLE
Deletion flow - ensure we have all resource deleted on destroy

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-rag-sample-da#22]

**Comment by vburckhardt** [comment]
Shouldn't the project in last screen be deleted as well?

**Comment by rajatagarwal-ibm** [comment]
It's deleted, when I refreshed the screen it shows me those notices in the red

**Comment by rajatagarwal-ibm** [comment]
Closing this issue...

**Comment by rajatagarwal-ibm** [comment]
After discussing with @brendankellyibm it looks like the projects are not getting deleted, but the instances they are on are. I will work on to make sure the projects are deleted too.

**Comment by ocofaigh** [comment]
Per Brendan:

this is fixed now - assistant should be destroyed upon undeploy, as we have proper deletion scripts for it now.
