### ISSUE TITLE
Variables declaration missing from ibmcatalog.json

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-rag-sample-da#233]
This results in variables missing when importing in new catalog tile. This also means that the ordering currently present in the public community tile was implemented through UI, so not reflected "as code"

**Comment by ocofaigh** [comment]
@vburckhardt FYI, when you import in the UI you need to select the option to import all variables to ensure all of them get added. We do it automatically in the pipeline using CLI option `--include-config` when running import command.

But agree, the missing vars do need to be added to the catalog json for sorting

**Comment by ocofaigh** [comment]
Looks like we are already tracking this in https://github.com/terraform-ibm-modules/terraform-ibm-rag-sample-da/issues/90
