### ISSUE TITLE
toolchain region used for the secret manager region

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-rag-sample-da#39]
https://github.com/terraform-ibm-modules/terraform-ibm-rag-sample-da/blob/8fbf807993b82687360f9da9b69dc20c1af67a70/solutions/banking/main.tf#L54

This will prevent use case where sm is in a different region

**Comment by rajatagarwal-ibm** [comment]
https://github.com/terraform-ibm-modules/terraform-ibm-rag-sample-da/pull/41
