### ISSUE TITLE
secret_manager_crn is not used (just outputted)

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-rag-sample-da#40]
https://github.com/terraform-ibm-modules/terraform-ibm-rag-sample-da/blob/8fbf807993b82687360f9da9b69dc20c1af67a70/solutions/banking/variables.tf#L104

suggest to remove if not using it

**Comment by rajatagarwal-ibm** [comment]
https://github.com/terraform-ibm-modules/terraform-ibm-rag-sample-da/pull/41
