### ISSUE TITLE
Add option to skip creating secrets in sm

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-rag-sample-da#50]
### Description

- Add a bool allowing to skip creation of secrets (on single input sufficient for the 2 secrets)
- To cover the use case where existing sm is reused.
- Needed in RAG DA to cover some inflexibilities in Project handling of stacks (ideally we should be able to compute this based on input of the stack.)

**Comment by rajatagarwal-ibm** [comment]
https://github.com/terraform-ibm-modules/terraform-ibm-rag-sample-da/pull/51

**Comment by rajatagarwal-ibm** [comment]
PR merged
