### ISSUE TITLE
Create secrets through the private endpoint

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-rag-sample-da#68]
### Description

A change in the sm da creates a sm instance that is private only.

This result in the following error. Setting the endpoint type to private by default at https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/sm_arbitrary_secret#endpoint_type would solve the issue. all sm instance have private endpoint. Expose the endpoint type variable on the module so that it can be set to public in the github pipelines.

```
 2024/05/16 21:09:51 Terraform apply | Error: CreateSecretWithContext failed Post "https://a10e24e5-2810-4972-a23e-798a49905c23.us-south.secrets-manager.appdomain.cloud/api/v2/secrets": dial tcp: lookup a10e24e5-2810-4972-a23e-798a49905c23.us-south.secrets-manager.appdomain.cloud on 172.21.0.10:53: no such host
 2024/05/16 21:09:51 Terraform apply | null
 2024/05/16 21:09:51 Terraform apply | 
 2024/05/16 21:09:51 Terraform apply | 
 2024/05/16 21:09:51 Terraform apply |   with module.secrets_manager_secret_ibm_iam[0].ibm_sm_arbitrary_secret.arbitrary_secret[0],
 2024/05/16 21:09:51 Terraform apply |   on .terraform/modules/secrets_manager_secret_ibm_iam/main.tf line 37, in resource "ibm_sm_arbitrary_secret" "arbitrary_secret":
 2024/05/16 21:09:51 Terraform apply |   37: resource "ibm_sm_arbitrary_secret" "arbitrary_secret" {
 2024/05/16 21:09:51 Terraform apply | 
 2024/05/16 21:09:51 Terraform apply | 
 2024/05/16 21:09:51 Terraform apply | Error: CreateSecretWithContext failed Post "https://a10e24e5-2810-4972-a23e-798a49905c23.us-south.secrets-manager.appdomain.cloud/api/v2/secrets": dial tcp: lookup a10e24e5-2810-4972-a23e-798a49905c23.us-south.secrets-manager.appdomain.cloud on 172.21.0.10:53: no such host
```

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by rajatagarwal-ibm** [comment]
It fails with the same error after using the `private` endpoint type for the secrets. See https://github.com/terraform-ibm-modules/terraform-ibm-rag-sample-da/actions/runs/9122754264/job/25084170583

**Comment by ocofaigh** [comment]
@rajatagarwal-ibm Is the test being run in a runtime that has access to private endpoint (aka in schematics) ?

**Comment by rajatagarwal-ibm** [comment]
No - it's not. That's the reason it failed. Should be fine in the catalog
