### ISSUE TITLE
Change name of DA to Sample Retrieval Augmented Generation App Config

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-rag-sample-da#9]
https://github.com/terraform-ibm-modules/terraform-ibm-rag-sample-da/blob/534aca20438190b29e9d3a4ca6917d4b971e2326/ibm_catalog.json#L4

**Comment by rajatagarwal-ibm** [comment]
PR created https://github.com/terraform-ibm-modules/terraform-ibm-rag-sample-da/pull/16

**Comment by rajatagarwal-ibm** [comment]
PR merged
